### ISSUE TITLE
OnAppOpenAttribution method has been never called by XamarinAndroidBinding.

### ISSUE THREAD

**Issue by vinhtek** [AppsFlyerSDK/XamarinAndroidBinding#13]
I have added the intent filter to activity and build a Onelink using Android AppLink in portal. When clicking on Onelink, it redirects to my app. I follow Appsflyer log and see only as below:

[AppsFlyer_5.1.1] Calling onConversionDataSuccess with:
[AppsFlyer_5.1.1] {install_time=2020-07-10 08:44:28.384, af_status=Organic, af_message=organic install, is_first_launch=false}

I don't see any OnAppOpenAttribution calling. Please help.

**Comment by sokoloff06** [comment]
Please open a ticket to our Support Team if this is still relevant, they should be able to assist with he implementation or confirm if there is a bug in the binding/native library. Thank you!
