### ISSUE TITLE
Sample app doesn't pass Android SDK integration test.

### ISSUE THREAD

**Issue by vadzim-vys** [AppsFlyerSDK/XamarinAndroidBinding#8]
Steps to reproduce:

1. Setup correct package name, api key, build and install sample app to whitelist device.
2. Install [AppsFlyer SDK test](https://play.google.com/store/apps/details?id=com.appsflyer.referrerSender)
3. Select sample app at AppsFlyer SDK test.
4. Run "SDK INTEGRATION TEST"

Expected result: test passed.
Actual result: test not passed. 

AppsFlyer test app shows you a warning that broadcast receiver wasn't found at manifest.
When you click continue, you get following error:
Oops, this app can not be monitored, Please make sure that: 
1. You are using a supported AppsFlyer SDK version.
2. AppsFlyer's BroadcastReceiver is configured.
3. startTracking() is placed in the MainActivity

**Comment by vadzim-vys** [comment]
Setting the BroadcastReceiver in AndroidManifest.xml doesn't help.
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.insert.your.package.name.here">
	<uses-sdk android:minSdkVersion="10" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<application android:allowBackup="true" android:icon="@mipmap/icon" android:label="@string/app_name">
        <receiver android:name="com.appsflyer.SingleInstallBroadcastReceiver" android:exported="true">
            <intent-filter>
                 <action android:name="com.android.vending.INSTALL_REFERRER" />
             </intent-filter>
        </receiver>
    </application>
</manifest>
````

**Comment by dhivadeekshi** [comment]
Hello, we are also facing the same issue. We are getting the error in random.
The test seems to work around 40% of the time, rest we get the error.
We are using the latest Appsflyer Unity plugin v4.16.4

**Comment by sirfarmalot** [comment]
Does this Binding actually work?

**Comment by vadzim-vys** [comment]
@sirfarmalot, yes, we're using it at production, so we tested integration manually, and now we see installs at dashboard

**Comment by defic** [comment]
We are having the same issue with the Unity SDK. I was using the sample app for Unity.
https://github.com/AppsFlyerSDK/SampleApp-Examples

Running the AppsFlyer SDK Integration Test app from playstore with the exact same steps and the same error.

I hope the error is just with the integration test app.

**Comment by sokoloff06** [comment]
The integration test app for Android was deprecated, please use the new Integration Test Page on the Appsflyer app Dashboard. Closing as no longer relevant, thanks!
