### ISSUE TITLE
Deep Linking Fails Integration Tests

### ISSUE THREAD

**Issue by chrisdrysdale** [AppsFlyerSDK/XamarinAndroidBinding#9]
After adding `AppsFlyerLib.Instance.SendDeepLinkData(this)` within my MainActivity.OnCreate method I am always getting a Fail when using the SDK Integration Test app.  My manifest contains the necessary activity intent-filter with a scheme set and the app will open when running the test, but it will always return a Fail status with "Please make sure that sendDeepinkData() is present in your deeplinked activity".

**Comment by sirfarmalot** [comment]
Does this Binding Actually Work?

**Comment by sokoloff06** [comment]
The integration test app for Android was deprecated, please use the new Integration Test Page on the Appsflyer app Dashboard. Closing as no longer relevant, thanks!
